{{- if .Values.gitlab }}
kind: Route
apiVersion: v1
metadata:
  name: {{ $.Values.gitlab_app_name }}
  labels:
    app: {{ $.Values.gitlab_app_name }}
spec:
  host: {{ .Values.gitlab.host_name }}
  to:
    kind: Service
    name: {{ $.Values.gitlab_app_name }}
  port:
    targetPort: 443-https
  tls:
    termination: passthrough
  wildcardPolicy: None
{{- end }}
